services:
  jupyterlab:
    image: quay.io/jupyter/pytorch-notebook:2025-12-31
    container_name: jupyterlab
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ./data:/home/jovyan/work:rw
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - DOCKER_STACKS_JUPYTER_CMD=lab
      - CHOWN_EXTRA=/home/jovyan/work
      - CHOWN_EXTRA_OPTS=-R
      # 是否自动生成证书
      - GEN_CERT=yes
      # 以 root 运行，保持默认用户但授予 sudo
      - GRANT_SUDO=yes
    # pwd: admin
    command: |
      start-notebook.py --ServerApp.base_url=/ --allow-root
      --ServerApp.password='argon2:$$argon2id$$v=19$$m=10240,t=10,p=8$$3/9UgtjFysaSkaZ7Zzmryw$$K1nrBSMWztukex2+C+axtEdBJuHoTlHUEkldbXIdQGc'
    restart: unless-stopped
