baseURL = 'https://meimeitou.github.io/xbox/'
relativeURLs = true
canonifyURLs = true
languageCode = "zh-cn"
title = ''

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  disableLanguageSwitchingButton = true
  alwaysopen = false
  collapsibleMenu = true
  themeVariant = ['green', 'learn', 'relearn-light', 'relearn-dark']
  additionalContentLanguage = ['zh']
  showVisitedLinks = false

[params.author]
    emailname = '772006843@qq.com'
    name = 'meimeitou'

[caches]
  [caches.images]
    dir = ':cacheDir/images'