baseURL = 'https://meimeitou.github.io/xbox/'
relativeURLs = false
canonifyURLs = false
languageCode = "zh-cn"
title = 'Meimeitou'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [["$$", "$$"], ["\\[", "\\]"]]
          inline = [["$", "$"], ["\\(", "\\)"]]

[module]
  [[module.imports]]
    path = 'github.com/McShelby/hugo-theme-relearn'

[params]
  disableLanguageSwitchingButton = true
  alwaysopen = false
  collapsibleMenu = true
  themeVariant = ['green', 'learn', 'relearn-light', 'relearn-dark']
  additionalContentLanguage = ['zh']
  showVisitedLinks = false
  math = true

[params.author]
    emailname = '772006843@qq.com'
    name = 'meimeitou'

[caches]
  [caches.images]
    dir = ':cacheDir/images'